config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "homes#index"
  resources :profiles, only: [ :show ]
  resources :searches, only: [ :index ]

  resources :posts, except: :index do
    resources :comments, only: [ :create, :destroy ]
    resources :likes, only: [ :create, :destroy ]
  end
  resources :friend_requests, only: [ :create, :destroy ]
  post "friend_requests/:id/accept", to: "friend_requests#accept", as: "friend_requests_accept"
  resources :users, only: [ :index, :show ] do
    member do
      get "friend_requests", to: "users#friend_requests"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true, length: { maximum: 1000 }
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
  enum :status, [ :pending, :accepted, :rejected ]

  validates :sender_id, uniqueness: { scope: :receiver_id, message: "Friend request already sent" }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :file, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :file, presence: true
  validates :caption, length: { maximum: 2200 }

  def like_count
    likes.count
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :sent_friend_requests, class_name: "FriendRequest", foreign_key: "sender_id", dependent: :destroy
  has_many :received_friend_requests, class_name: "FriendRequest", foreign_key: "receiver_id", dependent: :destroy
  
  validates :username, presence: true, uniqueness: true, length: { in: 3..30 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  after_create_commit :new_user_welcome

  def self.ransackable_attributes(auth_object = nil)
    [ "username" ]
  end

  def new_user_welcome
    UserMailer.with(user: self).welcome_email.deliver_now
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def index
    @comments = @post.comments
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_to @post
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/homes_controller.rb
 class HomesController < ApplicationController
  def index
  end
 end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  def create
    @like = @post.likes.find_by(user: current_user)
    if @like
      @like.destroy
    else
      @post.likes.create(user: current_user)
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = @post.likes.find_by(user: current_user)
    @like.destroy if @like
    redirect_to @post
  end

  private
  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [ :show, :edit, :update, :destroy ]

  def show
    @comments = @post.comments
    @user = current_user
  end

  def new
    @post = Post.new
  end

  def create
      @post = current_user.posts.build(post_params)
      if @post.save
        redirect_to @post
      else
        render :new
      end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def like
      like = @post.likes.find_by(user: current_user)
  end

  def destroy
    @post.destroy
    redirect_to profile_path
  end

  private

  def post_params
    params.require(:post).permit(:caption, :file)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    if params[:query].present?
      @users = User.where("username LIKE ?", "%#{params[:query]}%")
    else
      @users = []
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
      @users = User.includes(posts: :comments).all
  end

  def show
      @user = User.find(params[:id])
      @friend_request = FriendRequest.new
      @q = User.ransack(params[:q])
      @users = @q.result(distinct: true).where.not(id: current_user.id)
  end

  def friend_requests
    @received_requests = current_user.received_friend_requests.pending
    @send_friends = current_user.sent_friend_requests.accepted
    @receive_friends = current_user.received_friend_requests.accepted
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<% if user_signed_in? %>
  <script type="text/javascript">
    window.location.href = "<%= users_path %>";
  </script>
  <%= button_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
  <div class="flex flex-col items-center justify-center h-screen bg-white">
    <h1 class="text-3xl font-bold mb-2">Welcome to Instagram</h1>
    <p class="text-gray-600 mb-4">Please register or sign in to continue.</p>
    <%= link_to 'Sign Up', new_user_registration_path, class: 'bg-green-500 text-white px-6 py-2 rounded-full shadow-md hover:bg-green-600' %>
    <%= link_to 'Sign In', new_user_session_path, class: 'bg-blue-500 text-black px-8 mt-3 py-3 rounded-full shadow-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-400 transition duration-200 transform hover:scale-105' %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<div class="p-8 rounded-xl shadow-lg max-w-4xl mx-auto mt-10 bg-white">
  <div class="flex items-center justify-between space-x-6">
    <div class="flex items-center space-x-4">
      <div class="w-24 h-24 rounded-full overflow-hidden shadow-lg">
        <% if @user.image.attached? %>
          <%= image_tag @user.image, class: "w-full h-full object-cover", alt: "User image" %>
        <% else %>
          <div class="flex items-center justify-center w-full h-full bg-gray-300 text-white text-3xl">
            <svg xmlns="https://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-12 h-12 text-gray-600">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12h3l-3-3m0 6h3l-3 3M3 9h3l-3 3m0 6h3l-3 3M5.5 7l1 1m13 13l1 1m-3-3l1-1m-8 8l1-1"></path>
            </svg>
          </div>
        <% end %>
      </div>
      <div>
        <p class="text-xl font-semibold text-gray-800"><%= @user.username %></p>
        <p class="text-sm text-gray-600 mt-1"><%= @user.bio %></p>
      </div>
    </div>
    <% if @user == current_user %>
      <div class="flex space-x-4">
        <%= link_to "Edit profile", edit_user_registration_path, class: "bg-indigo-600 hover:bg-indigo-700 text-white font-semibold py-2 px-6 rounded-full transition duration-200" %>
        <%= link_to "Create New Post", new_post_path, class: "bg-indigo-600 hover:bg-indigo-700 text-white font-semibold py-2 px-6 rounded-full transition duration-200" %>
      </div>
    <% end %>
  </div>

  <div class="mt-6">
    <h1 class="text-sm text-gray-500"><%= @user.posts.count %> Posts</h1>
  </div>
  <div class="mt-6">
    <h3 class="text-lg font-semibold text-gray-800 mb-4">Posts</h3>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
      <% @user.posts.each do |post| %>
        <div class="relative rounded-lg overflow-hidden shadow-lg">
          <%= link_to post_path(post) do %>
          <%if post.file.attached? %>
            <%if post.file.image?%>
            <%= image_tag url_for(post.file), alt: post.caption, class: "w-full h-64 object-cover rounded-lg transition duration-300 transform hover:scale-105" %>
            <%elsif post.file.video?%>
              <%= video_tag url_for(post.file), alt: post.caption, class: "w-full h-64 object-cover rounded-lg transition duration-300 transform hover:scale-105" %>
          <% end %>
          <%end%>
        <%end%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/searches/index.html.erb
<div class="container mx-auto p-4">
  <h1 class="text-2xl font-bold mb-4">Search Users</h1>

  <%= render 'searches/form' %>

  <% if @users.any?%>
    <h2 class="text-xl font-bold mb-4">Results</h2>
    <ul class="list-none">
      <% @users.each do |user| %>
        <li class="bg-gray-100 p-2 rounded mb-2">
      <strong>Username:</strong> <%= link_to user.username, profile_path(user) %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p class="text-gray-500">No results found.</p>
  <% end %>
</div>