config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "homes#index"
  resources :profiles, only: [ :show ]
  resources :searches, only: [ :index ]

  resources :posts, except: :index do
    resources :comments, only: [ :create, :destroy ]
    resources :likes, only: [ :create, :destroy ]
  end
  resources :friend_requests, only: [ :create, :destroy ]
  post "friend_requests/:id/accept", to: "friend_requests#accept", as: "friend_requests_accept"
  resources :users, only: [ :index, :show ] do
    member do
      get "friend_requests", to: "users#friend_requests"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true, length: { maximum: 1000 }
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
  enum :status, [ :pending, :accepted, :rejected ]

  validates :sender_id, uniqueness: { scope: :receiver_id, message: "Friend request already sent" }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :file, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :file, presence: true
  validates :caption, length: { maximum: 2200 }

  def like_count
    likes.count
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :sent_friend_requests, class_name: "FriendRequest", foreign_key: "sender_id", dependent: :destroy
  has_many :received_friend_requests, class_name: "FriendRequest", foreign_key: "receiver_id", dependent: :destroy
  
  validates :username, presence: true, uniqueness: true, length: { in: 3..30 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  after_create_commit :new_user_welcome

  def self.ransackable_attributes(auth_object = nil)
    [ "username" ]
  end

  def new_user_welcome
    UserMailer.with(user: self).welcome_email.deliver_now
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def index
    @comments = @post.comments
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_to @post
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/homes_controller.rb
 class HomesController < ApplicationController
  def index
  end
 end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  def create
    @like = @post.likes.find_by(user: current_user)
    if @like
      @like.destroy
    else
      @post.likes.create(user: current_user)
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = @post.likes.find_by(user: current_user)
    @like.destroy if @like
    redirect_to @post
  end

  private
  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [ :show, :edit, :update, :destroy ]

  def show
    @comments = @post.comments
    @user = current_user
  end

  def new
    @post = Post.new
  end

  def create
      @post = current_user.posts.build(post_params)
      if @post.save
        redirect_to @post
      else
        render :new
      end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def like
      like = @post.likes.find_by(user: current_user)
  end

  def destroy
    @post.destroy
    redirect_to profile_path
  end

  private

  def post_params
    params.require(:post).permit(:caption, :file)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
      @users = User.includes(posts: :comments).all
  end

  def show
      @user = User.find(params[:id])
      @friend_request = FriendRequest.new
      @q = User.ransack(params[:q])
      @users = @q.result(distinct: true).where.not(id: current_user.id)
  end

  def friend_requests
    @received_requests = current_user.received_friend_requests.pending
    @send_friends = current_user.sent_friend_requests.accepted
    @receive_friends = current_user.received_friend_requests.accepted
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Instagram " %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
<% if user_signed_in? %>
<body class="bg-gray-100">
  <nav class="bg-gray-900 text-white p-4">
    <div class="container mx-auto flex justify-between items-center">
      <%= link_to 'Instagram', root_path, class: "text-xl font-bold" %>
      <div class="flex space-x-4">
          <a href="/" class="hover:text-gray-300">Home</a>
          <a href="<%= friend_requests_user_path(current_user.id) %>" class="hover:text-gray-300">Friends</a>
          <a href="<%= profile_path(current_user.id) %>" class="hover:text-gray-300">Profile</a>
          <a href="<%= user_path(current_user.id) %>" class="hover:text-gray-300">Search</a>
          <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'hover:text-gray-300' %>
        <%end%>
      </div>
    </div>
  </nav>
  <%= yield %>
</body>